### ISSUE TITLE
How about other datasets like tiered-imagenet?

### ISSUE THREAD

**Issue by wangryhen** [titania7777/Pytorch_Sampler#1]

**Comment by titania7777** [comment]
Hi wangryhen
I have no plan to use tiered-imagenet, but I added customized labels for tiered-imagenet, so you may utilize tiered-imagenet now.

[mini-imagenet] 
--images-path = "/path/to/mini-imagenet/"
--labels-path = "/path/to/mini-imagenet/"

[tiered-imagenet] 
--images-path = "/path/to/tiered-imagenet/"
--labels-path = "/path/to/tiered-imagenet/"

Both datasets have the same directory-tree
```
+-- mini_imagenet or tiered_imagenet
|   +-- train
|   +-- val
|   +-- test
```
And here are where I get the source from
mini-imagenet label: https://github.com/yaoyao-liu/mini-imagenet-tools
tiered-imagenet label: https://github.com/yaoyao-liu/tiered-imagenet-tools
few-shot dataset: https://lyy.mpi-inf.mpg.de/mtl/download/

**Comment by wangryhen** [comment]
Dear Hyeok Yoon
Thanks a lot!





From: Hyeok Yoon ***@***.***>
Date: 2022-04-24 19:47:29
To: titania7777/MiniImageNetFewShot ***@***.***>
Cc: wangryhen ***@***.***>,Author ***@***.***>
Subject: Re: [titania7777/MiniImageNetFewShot] How about other datasets like tiered-imagenet? (Issue #1)

Hi wangryhen
 I have no plan to use tiered-imagenet, but I added customized labels for tiered-imagenet, so you may utilize tiered-imagenet now.
[mini-imagenet]
 --images-path = "/path/to/mini-imagenet/"
 --labels-path = "/path/to/mini-imagenet/"
[tiered-imagenet]
 --images-path = "/path/to/tiered-imagenet/"
 --labels-path = "/path/to/tiered-imagenet/"
Both datasets have the same directory-tree
+-- mini_imagenet or tiered_imagenet
|   +-- train
|   +-- val
|   +-- test
And here are where I get the source from
 mini-imagenet label: https://github.com/yaoyao-liu/mini-imagenet-tools
 tiered-imagenet label: https://github.com/yaoyao-liu/tiered-imagenet-tools
 few-shot dataset: https://lyy.mpi-inf.mpg.de/mtl/download/
